'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Users, Plus, Sparkles, Trash2, Edit3, ArrowRight, ShieldCheck, Check } from 'lucide-react';
import { Character, VisualStyle } from '@/lib/types';
import { VISUAL_STYLES } from '@/lib/presets';

export default function CharactersPage() {
  const router = useRouter();
  const [characters, setCharacters] = useState<Character[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [saving, setSaving] = useState(false);

  // Form State
  const [name, setName] = useState('');
  const [species, setSpecies] = useState('');
  const [gender, setGender] = useState('Boy');
  const [ageAppearance, setAgeAppearance] = useState('5-year-old child');
  const [traitsInput, setTraitsInput] = useState('');
  const [visualDna, setVisualDna] = useState('');
  const [style, setStyle] = useState<VisualStyle>('3d_pixar');

  const fetchCharacters = async () => {
    try {
      const res = await fetch('/api/characters');
      const data = await res.json();
      setCharacters(data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCharacters();
  }, []);

  const handleAutoGenerateDna = () => {
    if (!name || !species) {
      alert('Please enter Name and Species first!');
      return;
    }
    const traits = traitsInput.split(',').map(t => t.trim()).filter(Boolean);
    const dna = `cute little ${species.toLowerCase()} named ${name}, ${ageAppearance}, ${traits.join(', ')}, highly expressive cheerful face, friendly sparkling eyes, rounded soft shapes, iconic consistent signature outfit, lovable children mascot`;
    setVisualDna(dna);
  };

  const handleSaveCharacter = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || saving) return;
    setSaving(true);

    try {
      const traits = traitsInput.split(',').map(t => t.trim()).filter(Boolean);
      const res = await fetch('/api/characters', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name,
          species,
          gender,
          age_appearance: ageAppearance,
          traits,
          visual_dna: visualDna || `${name}, cute ${species}`,
          style
        })
      });

      if (res.ok) {
        setShowModal(false);
        resetForm();
        fetchCharacters();
      } else {
        alert('Failed to save character');
      }
    } catch (err: any) {
      alert('Error: ' + err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this character?')) return;
    await fetch(`/api/characters?id=${id}`, { method: 'DELETE' });
    fetchCharacters();
  };

  const resetForm = () => {
    setName('');
    setSpecies('');
    setGender('Boy');
    setAgeAppearance('5-year-old child');
    setTraitsInput('');
    setVisualDna('');
    setStyle('3d_pixar');
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
      
      {/* Top Bar */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
            <span className="badge badge-purple">Persistent Cast</span>
            <span className="badge badge-emerald">DNA Consistency Engine</span>
          </div>
          <h1 style={{ fontSize: '2rem', fontWeight: '800' }}>Character Workshop</h1>
          <p style={{ fontSize: '0.95rem', color: '#94A3B8' }}>
            Build and store recurring characters with locked Visual DNA prompts for 100% style and face consistency.
          </p>
        </div>

        <button 
          onClick={() => { resetForm(); setShowModal(true); }} 
          className="btn btn-primary"
        >
          <Plus size={18} />
          <span>Create New Character</span>
        </button>
      </div>

      {/* Consistency Explainer Banner */}
      <div className="glass-panel" style={{ padding: '20px 24px', background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.1) 0%, rgba(6, 182, 212, 0.1) 100%)', border: '1px solid rgba(139, 92, 246, 0.3)' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px' }}>
          <div style={{ padding: '8px', background: 'rgba(139, 92, 246, 0.2)', borderRadius: '10px', color: 'var(--accent-purple)' }}>
            <ShieldCheck size={24} />
          </div>
          <div>
            <h4 style={{ fontSize: '0.98rem', fontWeight: '700', marginBottom: '4px', color: '#F8FAFC' }}>
              How Visual Consistency Works in YTKids Studio
            </h4>
            <p style={{ fontSize: '0.82rem', color: '#94A3B8', lineHeight: 1.5 }}>
              Each character stores an unalterable <strong>&quot;Visual DNA&quot;</strong> text block (species, fur color, clothing, eye reflections, signature marks). When generating scenes or scripts, this DNA is injected into every single scene prompt so the character stays identical across infinite episodes!
            </p>
          </div>
        </div>
      </div>

      {/* Characters Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '24px' }}>
        {characters.map(char => (
          <div key={char.id} className="glass-panel" style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
            
            {/* Character Header / Avatar */}
            <div style={{ height: '180px', background: 'linear-gradient(135deg, #1E1B4B 0%, #0F172A 100%)', position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              {char.avatar_url ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={char.avatar_url} alt={char.name} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
              ) : (
                <div style={{ width: '80px', height: '80px', borderRadius: '20px', background: 'var(--grad-sunset)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem', fontWeight: '800' }}>
                  {char.name[0]}
                </div>
              )}
              <span className="badge badge-purple" style={{ position: 'absolute', top: '12px', left: '12px', fontSize: '0.7rem' }}>
                {char.style.replace('_', ' ').toUpperCase()}
              </span>
              <button 
                onClick={() => handleDelete(char.id)}
                style={{ position: 'absolute', top: '12px', right: '12px', background: 'rgba(0,0,0,0.6)', border: 'none', borderRadius: '8px', padding: '6px', color: '#EF4444', cursor: 'pointer' }}
                title="Delete Character"
              >
                <Trash2 size={16} />
              </button>
            </div>

            {/* Character Info */}
            <div style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '14px', flex: 1 }}>
              <div>
                <h3 style={{ fontSize: '1.25rem', fontWeight: '700', marginBottom: '4px' }}>{char.name}</h3>
                <p style={{ fontSize: '0.82rem', color: '#94A3B8' }}>
                  {char.species} • {char.gender} • {char.age_appearance}
                </p>
              </div>

              {/* Traits Tags */}
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                {char.traits?.map((t, idx) => (
                  <span key={idx} style={{ fontSize: '0.72rem', background: 'rgba(255,255,255,0.06)', padding: '3px 8px', borderRadius: '6px', color: '#CBD5E1' }}>
                    {t}
                  </span>
                ))}
              </div>

              {/* Visual DNA Box */}
              <div style={{ background: 'rgba(15, 23, 42, 0.7)', padding: '10px 12px', borderRadius: '10px', border: '1px solid var(--border-subtle)', marginTop: 'auto' }}>
                <span style={{ fontSize: '0.68rem', fontWeight: '700', color: '#FCD34D', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Locked Visual DNA:
                </span>
                <p style={{ fontSize: '0.75rem', color: '#94A3B8', marginTop: '4px', lineHeight: 1.4, maxHeight: '60px', overflowY: 'auto' }}>
                  &quot;{char.visual_dna}&quot;
                </p>
              </div>

              {/* Action Button */}
              <button 
                onClick={() => router.push(`/stories?char_id=${char.id}`)}
                className="btn btn-secondary" 
                style={{ width: '100%', fontSize: '0.85rem' }}
              >
                <Sparkles size={15} color="var(--accent-amber)" />
                <span>Create Story With {char.name}</span>
                <ArrowRight size={14} />
              </button>
            </div>

          </div>
        ))}
      </div>

      {/* Modal: Create Character */}
      {showModal && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0,0,0,0.8)',
          backdropFilter: 'blur(8px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 100,
          padding: '20px'
        }}>
          <div className="glass-panel" style={{
            maxWidth: '620px',
            width: '100%',
            maxHeight: '90vh',
            overflowY: 'auto',
            padding: '32px',
            background: 'var(--bg-secondary)',
            border: '1px solid rgba(255,255,255,0.15)'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h2 style={{ fontSize: '1.4rem', fontWeight: '800' }}>Create Recurring Character</h2>
              <button onClick={() => setShowModal(false)} className="btn btn-ghost" style={{ padding: '4px 8px' }}>✕</button>
            </div>

            <form onSubmit={handleSaveCharacter} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              
              <div style={{ display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: '12px' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: '600', marginBottom: '6px' }}>Name</label>
                  <input className="input-field" placeholder="e.g. Pip, Barnaby, Coco" value={name} onChange={e => setName(e.target.value)} required />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: '600', marginBottom: '6px' }}>Species / Type</label>
                  <input className="input-field" placeholder="e.g. Red Fox, Baby Owl, Boy" value={species} onChange={e => setSpecies(e.target.value)} required />
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '12px' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: '600', marginBottom: '6px' }}>Gender</label>
                  <select className="input-field" value={gender} onChange={e => setGender(e.target.value)}>
                    <option value="Boy">Boy</option>
                    <option value="Girl">Girl</option>
                    <option value="Gender Neutral">Gender Neutral</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: '600', marginBottom: '6px' }}>Age Appearance</label>
                  <input className="input-field" placeholder="e.g. 4-year-old child" value={ageAppearance} onChange={e => setAgeAppearance(e.target.value)} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: '600', marginBottom: '6px' }}>Art Style</label>
                  <select className="input-field" value={style} onChange={e => setStyle(e.target.value as VisualStyle)}>
                    {VISUAL_STYLES.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}
                  </select>
                </div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.82rem', fontWeight: '600', marginBottom: '6px' }}>
                  Signature Traits & Clothes (Comma separated)
                </label>
                <input 
                  className="input-field" 
                  placeholder="e.g. yellow sweater with heart patch, sparkling hazel eyes, fluffy tail" 
                  value={traitsInput} 
                  onChange={e => setTraitsInput(e.target.value)} 
                />
              </div>

              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <label style={{ fontSize: '0.82rem', fontWeight: '600' }}>Locked Visual DNA Prompt</label>
                  <button type="button" onClick={handleAutoGenerateDna} className="btn btn-ghost" style={{ fontSize: '0.75rem', padding: '2px 8px', color: 'var(--accent-purple)' }}>
                    ✨ Auto-Craft DNA
                  </button>
                </div>
                <textarea 
                  className="input-field textarea-field" 
                  placeholder="Detailed prompt description that gets passed to the AI on every scene..." 
                  value={visualDna} 
                  onChange={e => setVisualDna(e.target.value)} 
                  rows={3}
                />
              </div>

              <div style={{ display: 'flex', gap: '12px', marginTop: '12px' }}>
                <button type="button" onClick={() => setShowModal(false)} className="btn btn-secondary" style={{ flex: 1 }}>
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary" style={{ flex: 2 }} disabled={saving}>
                  {saving ? 'Creating & Generating Concept Art...' : 'Save Character to Cast'}
                </button>
              </div>

            </form>
          </div>
        </div>
      )}

    </div>
  );
}
